# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity', models.IntegerField(default=0)),
                ('status', models.TextField(choices=[('l', 'landed'), ('f', 'flying')], default='l')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('identifier', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-round',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Unknown event', max_length=50)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borders', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('simulation', 'round_number'),
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='ui_sim_interface.Simulation'),
        ),
        migrations.AddField(
            model_name='obstacle',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_sim_interface.Simulation'),
        ),
        migrations.AddField(
            model_name='event',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ui_sim_interface.Round'),
        ),
        migrations.AddField(
            model_name='drone',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drones', to='ui_sim_interface.Round'),
        ),
    ]
